name: Build and Deploy Rust Web Server

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  say_hello:
      runs-on: ubuntu-latest
      steps:
        - name: Install Rust
          uses: dtolnay/rust-toolchain@stable
          with:
            targets: x86_64-unknown-linux-musl

        - name: Checkout
          uses: actions/checkout@v3

        - name: Get Release Version From the Tag
          shell: bash
          run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV