name: Build and Deploy Rust Web Server

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_and_upload:
      runs-on: ubuntu-latest
      steps:
        - name: Install Rust
          uses: dtolnay/rust-toolchain@stable
          with:
            targets: x86_64-unknown-linux-musl

        - name: Checkout
          uses: actions/checkout@v3

        - name: Get Release Version From the Tag
          shell: bash
          run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

        - name: Build
          uses: actions-rs/cargo@v1
          with:
            use-cross: true
            command: build
            args: --verbose --release --target x86_64-unknown-linux-musl
          
        - name: Package
          shell: bash
          run: |  
            dirname="test-${{ env.VERSION }}-x86_64-unknown-linux-musl"
            mkdir "$dirname"

            mv "target/x86_64-unknown-linux-musl/release/test" "$dirname"
  
            tar -czf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV

        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            files: |
              ${{ env.ASSET }}